baseURL = "https://mauricebauer.de/"
defaultContentLanguage = "en"
locale = "en"

title = "Maurice Bauer"

theme = "gokarna"

# Automatically generate robots.txt
enableRobotsTXT = true

[params]
  footer = "Maurice Bauer"
  description = "Software Developer and Cybersecurity Analyst"
  avatarURL = "/images/me.jpg"
  avatarAltText = "Avatar"
  avatarSize = "size-m"
  socialIcons = [
    {name = "linkedin", url = "https://www.linkedin.com/in/maurice-bauer-660337263"},
    {name = "xing", url = "https://www.xing.com/profile/Maurice_Bauer7"},
    {name = "github", url = "https://github.com/mauricebauer"}
  ]
  metaKeywords = ["blog", "portfolio", "developer", "Maurice", "Bauer"]